import "./style.css";
import LanguageDetect from "languagedetect";
import './Plots/population.js'
import './Plots/WordsADay.js'
import loadAndPlotPopulation from "./Plots/population.js";
import loadAndPlotWords from "./Plots/WordsADay.js";
import loadAndPlotEnglishSpeakers from "./Plots/EnglishSpeakers.js";
import loadAndPlotAllWords from "./Plots/AIWords.js"

document.addEventListener("DOMContentLoaded", () => {
    loadAndPlotPopulation();
    loadAndPlotWords();
    loadAndPlotEnglishSpeakers();
    loadAndPlotAllWords();
    const toggle = document.querySelector('.disclaimer-toggle');
    const content = document.querySelector('.disclaimer-content');

    toggle.addEventListener('click', function () {
        this.classList.toggle('active');

        if (content.style.display === 'block') {
            content.style.display = 'none';
        } else {
            content.style.display = 'block';
        }
    });
});

document.querySelector("#title").innerHTML = `
    <h1>The World's Most Accurate* AI Text Detector</h1>
    <p class="read-the-docs">* Which really doesn't mean much</p>
`;

document.querySelector("#input").innerHTML = `
    <div class="input-container">
        <textarea id="text-input" rows="15" cols="100" placeholder="Enter at least 40 words of English text..."></textarea>
    </div>
`;


document.querySelector("#input").innerHTML = `
    <div class="input-container">
        <textarea id="text-input" rows="15" cols="100" placeholder="Enter at least 40 words of English text..." style="display: block; margin-bottom: 10px;"></textarea>
        <button id="check-button" style="display: block; margin: 0 auto;" disabled>Check for AI</button>
        <p id="error-message" style="color: red; display: none; text-align: center;"></p>
    </div>
`;


document.querySelector("#article").innerHTML = `
    <div class="formula">
    $$P_{\\text{AI}}(t) = \\frac{\\int_{t_0}^{t} \\text{AI}(\\tau) \\, d\\tau}{\\int_{t_0}^{t} \\text{AI}(\\tau) \\, d\\tau + \\int_{t_0}^{t} W(\\tau) \\, d\\tau}$$
</div>
    <p>Where:</p>
    <ul>
        <li>$P_{AI}(t):$ Probability a random word is AI-generated by year</li>
        <li>$AI(t):$ AI-generated words per day at time $t$</li>
        <li>$W(t):$ Human-generated words per day at time $t$</li>
        <li>$t_0:$ Starting year for integration (1500 for us)</li>
    </ul>
    <div class="disclaimer-container">
      <button class="disclaimer-toggle">Disclaimer</button>
      <div class="disclaimer-content">
        <p>This is nothing more than a thought experiment and guesswork and while I am employed at a company that works primarily with Generative AI, I tried to be as objective as possible with my estimation and basic guesswork.
        
        That being said, the views expressed here are solely my own.</p>
      </div>
    </div>
    In order to calculate the number of human-generated words until today, we will have to set some constraints:
    <ol>
    <li>We are only considering English for simplicity.</li>
    <li>We are only considering the timeframe from 1500 until 2100</li>
</ol>
    <h2>Part I: Human-Generated Words ($W(t)$)</h2>
    <div class="formula">$$W(t) = H(t) \\times E(t) \\times G(t)$$
</div>

    <h3>1. Human Population ($H(t)$)</h3>
    <p>This is by far the easiest function to model, since very smart people have gathered data from the past and have projected it for the future.</p>
    <p>All we have to do is a cubic interpolation on the datapoints:</p>
<canvas id="populationChart" width="800" height="300"></canvas>
    <h3>2. Fraction of Literate English Speakers ($E(t)$)</h3>
    <p>This one is a little harder, but still doable. We have data for recent years and will consider a datapoint cited in a paper in 2004 that put the English speaking fraction at ~9% in 1950.</p>
    <div class="formula">$$
E(t) = \\frac{E_{\\text{max}}}{1 + e^{-k_E (t - t_E)}}$$
<p>
Where:
$$E_{\\text{max}} = 0.33, \\quad k_E = 0.014, \\quad t_E = 2016$$
</p>
</div>
<canvas id="speakersChart" width="800" height="300"></canvas>
    <h3>3. Words per Person ($G(t)$)</h3>
    <p>Here we are getting into the solid guesswork territory. In order to calculate the number of words the average literate person writes per day, we need some underlying data.</p>
    <p>To generate the data, I asked different reasoning LLMs to come up with an estimate and put the average data points in here. They came up with remarkably similar numbers.</p>
    <div class="formula">$$
G(t) = \\left( \\frac{G_{\\text{max}}}{1 + e^{-k_G (t - t_G)}} + 15 \\right) \\times \\left(1 - r_{\\text{AI}}\\right)^{\\max(0, t - t_{\\text{AI}})}$$
<p>
Where:
$$G_{\\text{max}} = 1600, \\quad k_G = 0.06, \\quad t_G = 1985$$
$$r_{\\text{AI}} = 0.005, \\quad t_{\\text{AI}} = 2023$$
</p>
</div>
<canvas id="wordsChart" width="800" height="300"></canvas>
    <h2>Part II: AI-Generated Words ($AI(t)$)</h2>
    <div class="formula">
    $$AI(t) = \\text{AllText}(t) \\times \\text{EngShare}(t) \\times \\text{TxtShare}(t)$$
</div>

<h3>1. Total Visible AI Text</h3>
<div class="formula">
  $$\\text{AllText}(t) = \\frac{W_{\\text{max}}}{1 + e^{-k(t - t_{\\text{mid}})}} $$
  <p>
    Where:
    $$W_{\\text{max}} = 3.0 \\times 10^{12}, \\quad k = 2.1, \\quad t_{\\text{mid}} = 2025.5 $$
  </p>
</div>
    <h3>2. English Language Share</h3>
    <div class="formula">
    $$\\text{EngShare}(t) = \\max\\left( E_{\\text{floor}},\\ E_{\\text{start}} - r_E (t - 2023) \\right)$$
<p>
Where:
$$E_{\\text{start}} = 0.80, \\quad r_E = 0.02, \\quad E_{\\text{floor}} = 0.50$$
</p>
</div>
    <h3>3. Text Modality Share</h3>
    <div class="formula">$$\\text{TxtShare}(t) = \\max\\left( T_{\\text{floor}},\\ 1 - r_T \\cdot \\max(0,\\ t - t_T) \\right)$$
<p>
Where:
$$t_T = 2028, \\quad r_T = 0.01, \\quad T_{\\text{floor}} = 0.60$$
</p>
</div>
<canvas id="AIWords" width="800" height="300"></canvas>
<p>If we compare the </p>
<canvas id="combined" width="800" height="300"></canvas>
`;

const lngDetector = new LanguageDetect();
const textInput = document.getElementById("text-input");
const errorMessage = document.getElementById("error-message");
const checkButton = document.getElementById("check-button");

textInput.addEventListener("input", validateInput);

function validateInput() {
    const text = textInput.value.trim();
    const wordCount = text.split(/\s+/).filter(word => word.length > 0).length;
    let error = "";
    let isError = false;

    // Check word count
    if (wordCount < 40 && text.length > 0) {
        error = "Minimum 40 words required";
        isError = true;
    }

    // Check language (only if we have enough words)
    if (!isError && wordCount >= 40) {
        const detectedLanguage = lngDetector.detect(text, 1);
        if (detectedLanguage.length === 0 || detectedLanguage[0][0] !== "english") {
            error = "Only English text is supported";
            isError = true;
        }
    }

    if (isError) {
        showError(error);
        disableButton();
    } else {
        hideError();
        enableButton();
    }

    // Disable button if input is empty
    if (text.length === 0) {
        disableButton();
    }
}

function showError(message) {
    textInput.style.border = "2px solid red";
    errorMessage.style.display = "block";
    errorMessage.textContent = message;
}

function hideError() {
    textInput.style.border = "";
    errorMessage.style.display = "none";
    errorMessage.textContent = "";
}

function disableButton() {
    checkButton.disabled = true;
    checkButton.style.opacity = "0.5"; // Optional: Visual indicator for disabled button
}

function enableButton() {
    checkButton.disabled = false;
    checkButton.style.opacity = "1"; // Optional: Visual indicator for enabled button
}